//==================== FLEX TV - MAIN JS ====================
//==================== FLEXSHIELD ADBLOCK ====================
(function(){const nO=window.open;window.open=function(u,t,f){if(!u)return null;try{const d=new URL(u,window.location.href);if(d.origin===window.location.origin||u.includes('player.html')||u.includes('filter.html')||u.includes('index.html')){return nO.apply(window,arguments);}}catch(e){}console.warn('[FlexShield] Blocked:',u);return null;};document.addEventListener('click',function(e){let n=e.target;while(n&&n!==document){if(n.tagName==='A'){const h=n.getAttribute('href');if(h&&!h.startsWith('#')&&!h.startsWith('javascript:')){try{const tu=new URL(h,window.location.href);if(tu.origin!==window.location.origin&&!h.includes('index.html')&&!h.includes('filter.html')&&!h.includes('player.html')){e.preventDefault();e.stopPropagation();console.warn('[FlexShield] Blocked click:',h);return false;}}}catch(err){}}n=n.parentNode;}},true);})();
function showAd(){const m=document.getElementById('adblockStatusModal');if(m)m.classList.remove('hidden');}
function hideAd(){const m=document.getElementById('adblockStatusModal');if(m)m.classList.add('hidden');}

//==================== PARTICLE CANVAS ====================
let canvas,ctx,particles=[],cTheme='dust';
function initCanvas(){canvas=document.getElementById('bg-canvas');if(!canvas)return;ctx=canvas.getContext('2d');resizeC();window.addEventListener('resize',resizeC);initP();animateP();}
function resizeC(){if(!canvas)return;canvas.width=window.innerWidth;canvas.height=window.innerHeight;}
class Particle{constructor(t){this.t=t;this.reset();this.y=Math.random()*(canvas?canvas.height:500);}reset(){this.x=Math.random()*(canvas?canvas.width:500);this.a=Math.random()*Math.PI*2;this.s=Math.random()*3+1;this.sy=Math.random()*1+0.2;this.sx=(Math.random()-0.5)*1;this.o=Math.random()*0.4+0.1;this.sp=(Math.random()-0.5)*0.1;this.c='#ffffff';if(this.t==='sakura'){this.y=-50;this.s=Math.random()*5+4;this.sy=Math.random()*2+1;this.sx=Math.random()*2+1;this.o=Math.random()*0.5+0.3;this.c='#ffb7c5';}else if(this.t==='hearts'){this.y=(canvas?canvas.height:500)+50;this.s=Math.random()*8+6;this.sy=-(Math.random()*1.5+0.5);this.sx=(Math.random()-0.5)*1;this.o=Math.random()*0.4+0.2;this.c='#e50914';}else if(this.t==='horror'){this.y=Math.random()*(canvas?canvas.height:500);this.s=Math.random()*160+60;this.sy=(Math.random()-0.5)*0.4;this.sx=(Math.random()-0.5)*0.8;this.o=Math.random()*0.06+0.02;this.c='rgba(30,70,90,0.8)';}}update(){this.x+=this.sx;this.y+=this.sy;this.a+=this.sp;const h=canvas?canvas.height:500;const w=canvas?canvas.width:500;if(this.t==='sakura'||this.t==='hearts'){if(this.y<-50||this.y>h+50||this.x<-50||this.x>w+50)this.reset();}else{if(this.y<-300||this.y>h+300||this.x<-300||this.x>w+300)this.reset();}}draw(){if(!ctx)return;ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.a);ctx.globalAlpha=Math.min(this.o,1);if(this.t==='sakura'){ctx.fillStyle=this.c;ctx.beginPath();ctx.ellipse(0,0,this.s,this.s/2,0,0,Math.PI*2);ctx.fill();}else if(this.t==='hearts'){ctx.fillStyle=this.c;ctx.beginPath();let w=this.s,h=this.s;ctx.moveTo(0,h/4);ctx.bezierCurveTo(0,0,-w/2,0,-w/2,h/4);ctx.bezierCurveTo(-w/2,h/2,0,h*3/4,0,h);ctx.bezierCurveTo(0,h*3/4,w/2,h/2,w/2,h/4);ctx.bezierCurveTo(w/2,0,0,0,0,h/4);ctx.fill();}else if(this.t==='horror'){const g=ctx.createRadialGradient(0,0,0,0,0,this.s);g.addColorStop(0,'rgba(30,70,90,0.8)');g.addColorStop(1,'rgba(30,70,90,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,this.s,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(0,0,this.s,0,Math.PI*2);ctx.fill();}ctx.restore();}}
function initP(){particles=[];let c=50;if(cTheme==='horror')c=20;for(let i=0;i<c;i++)particles.push(new Particle(cTheme));}
function animateP(){if(!ctx)return;if(cTheme==='horror'){ctx.fillStyle='rgba(10,15,20,0.3)';ctx.fillRect(0,0,canvas.width,canvas.height);}else{ctx.clearRect(0,0,canvas.width,canvas.height);}particles.forEach(p=>{p.update();p.draw();});requestAnimationFrame(animateP);}
function updateTheme(t){let nt='dust';if(t==='anime')nt='sakura';else if(t==='horror')nt='horror';else if(t==='romance')nt='hearts';if(nt!==cTheme){cTheme=nt;initP();}}

//==================== SPLASH SCREEN ====================
function hideSplash(){const s=document.getElementById('splash-screen');if(!s)return;s.classList.add('splash-fade');setTimeout(function(){s.style.display='none';},800);}

//==================== MOBILE SEARCH ====================
function focusSearch(){const i=document.getElementById('searchInput');if(i){i.scrollIntoView({behavior:'smooth',block:'center'});i.focus();}}

//==================== INIT ====================
document.addEventListener('DOMContentLoaded',function(){initCanvas();setTimeout(hideSplash,600);});